celery_status = ('Возможные статусы:\n\n'
     'SUCCESS: Задача успешно завершилась и вернула результат.\n'
     'STARTED: Задача начала выполняться.\n\t'
     'Требует: Явное включение task_track_started = True в конфигурации\n'
     'RECEIVED: Worker получил задачу и готовится к её выполнению.\n'
     'PENDING: Задача ожидает выполнения.\n\t'
     'Причины:\n\t\t'
     'Задача ещё не была обработана worker`ом.\n\t\t'
     'Worker недоступен.\n\t\t'
     'Задача не зарегистрирована (ошибка конфигурации или имени задачи)\n'
     'FAILURE: Задача завершилась с исключением (ошибкой выполнения).\n'
     'RETRY: Задача потерпела временную неудачу и была запланирована на повторное выполнение.\n\t'
     'Причина: Бросок исключения self.retry(...) внутри задачи.\n'
     'REVOKED: Задача была отменена до начала или во время выполнения.\n\t'
     'Как вызвать: Метод revoke() на объекте AsyncResult\n'
     'fIGNORED (редко используется): Результат задачи был проигнорирован (например, в случае ignore_result = True).\n')

